# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD MAUI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  
  setup:
    runs-on: windows-latest
    steps:
    - name: Chaclout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install .NET MAUI workloads
      run: dotnet workload install maui

  build:
    name: Build MAUI for Android and IOS
    needs: [setup]
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
        target-framework: [net8.0-android, net8.0-ios]
    steps:
    - name: Checkout code  
      uses: actions/checkout@v4
    - name: Restore dependencies
      run: dotnet restore RoadTripPlannerApp/RoadTripPlannerApp.csproj
    - name: Build
      run: dotnet build RoadTripPlannerApp/RoadTripPlannerApp.csproj --no-restore -f ${{ matrix.target-framework }}

  test:
    needs: [build]
    runs-on: windows-latest
    steps:
    - name: Checkout code  
      uses: actions/checkout@v4  
    - name: Test
      run: dotnet test
      working-directory: ./RoadTripPlannerAppTest

  analysis:
    needs: [build]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout code  
      uses: actions/checkout@v4 
      # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    #- name: Autobuild
      #uses: github/codeql-action/autobuild@v3
    - name: Build project
      run: dotnet build
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"


  deployDev:
    name: Deploy to Development
    # Job runs only if the event is a pull request
    if: github.event_name == 'pull_request'
    # The job needs the test job to pass first
    needs: [ test ]
    runs-on: ubuntu-latest
    # Define some environment variables
    environment: 
      # The environment name must match the envrionment name in the repository
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Your code is being deployed to http://dev.myapp.com
  
  # Our deployment to staging environment
  deployStaging:
    name: Deploy to Staging
    # deploy to staging only if we are committing to main
    if: github.event.ref == 'refs/heads/main'
    needs: [ test ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
    - name: Deploy
      run: echo I am deploying to staging http://test.myapp.com
  
  # Deploy to production environment
  deployProduction:
    name: Deploy to Production
    needs: [ deployStaging ]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to production
